services:
  - type: web
    name: sphandcrafted
    env: node
    rootDir: app
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
    plan: free
